---
- name: elb
  hosts: localhost
  tasks:
                    - elb_application_lb_info:
                            region: ap-northeast-2
                      register: elb
- name: web
  hosts: _web
  become: true
  vars:
          ansible_ssh_private_key_file: fox-key
  tasks:
          - name: apache2
            apt:
                    name: apache2
                    state: latest
          - name: start
            service:
                    name: apache2
                    state: started
                    enabled: true
            ignore_errors: true
          - name: proxy
            blockinfile:
                    dest: /etc/apache2/sites-available/000-default.conf
                    content: |
                            ProxyRequests Off
                            ProxyPreserveHost On
                            <Proxy *>
                                    Order deny,allow
                                    Allow from all
                            </Proxy>
                            ProxyPass / http://{{ item.dns_name }}:8080/
                            ProxyPassReverse / http://{{ item.dns_name }}:8080/
                    insertbefore: "^</VirtualHost>$"
            with_items: '{{ hostvars["localhost"]["elb"].load_balancers }}'
            when: item.type  == "network"
          - name: proxy2
            command: a2enmod proxy_http
          - name: proxy3
            systemd:
                    name: apache2
                    state: restarted
                    enabled: true