- name: web
  hosts: _web
  become: true
  vars:
          ansible_ssh_private_key_file: fox-key.pem
  tasks:
          - name: httpd
            yum:
                    name: httpd
                    state: present
          - name: start
            service:
                    name: httpd
                    state: started
                    enabled: true