- name: nbl
  hosts: localhost
  tasks:
          - elb_application_lb_info:
                    region: ap-northeast-2
            register: nlb
- name: web
  hosts: _web
  become: true
  vars:
          ansible_ssh_private_key_file: fox-key
  tasks:
          - name: httpd
            yum:
                    name: httpd
                    state: present
          - name: create index.html
            copy:
                    src: index.html
                    dest: /var/www/html/index.html
          - name: proxy
            copy:
                    dest: /etc/httpd/conf.d/proxy.conf
                    content: |
                        <IfModule mod_proxy.c>
                            ProxyRequests Off
                            ProxyPreserveHost On
                            <Proxy *>
                                    Require all granted
                            </Proxy>
                            ProxyPass / http://{{ item.dns_name }}:8080/
                            ProxyPassReverse / http://{{ item.dns_name }}:8080/
                        </IfModule>
            with_items: '{{ hostvars["localhost"]["nlb"].load_balancers }}'
            when: item.type  == "network"
          - name: start
            service:
                    name: httpd
                    state: restarted
                    enabled: true
